# Generated by Django 5.2.6 on 2025-09-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_price', models.FloatField()),
                ('product_description', models.TextField()),
                ('product_photo', models.ImageField(upload_to='products/')),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('user_age', models.IntegerField()),
                ('user_city', models.CharField(max_length=100)),
                ('user_hobby', models.CharField(max_length=100)),
                ('user_food', models.CharField(max_length=100)),
            ],
        ),
    ]
