# Generated by Django 5.2.6 on 2025-09-19 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ['product_name'], 'verbose_name_plural': 'Products'},
        ),
    ]
